source 'https://rubygems.org'

# Specify your gem's dependencies in codexrb.gemspec
gemspec


gem 'ast', '~> 2.3'
# gem 'jazz_hands', github: 'nixme/jazz_hands', branch: 'bring-your-own-debugger'
gem 'logging', '~> 2.1'
gem 'parser', '~> 2.3'
gem 'pry-byebug', '~> 1.3'
gem 'thor', '~> 0.19'

